// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_dMvdOAumuFUsjywOvBeMxQlIFu55BP0',
    appId: '1:349157902224:web:f5d4ff38dca160e3415515',
    messagingSenderId: '349157902224',
    projectId: 'springbootflutterfirebase',
    authDomain: 'springbootflutterfirebase.firebaseapp.com',
    storageBucket: 'springbootflutterfirebase.firebasestorage.app',
    measurementId: 'G-BKQCE2ZNE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDpy7puikk9DcmPeJK9jLJpXGZ_gLM3f0',
    appId: '1:349157902224:android:e8c03f62fa50c219415515',
    messagingSenderId: '349157902224',
    projectId: 'springbootflutterfirebase',
    storageBucket: 'springbootflutterfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvi_su4tGZ67kUpTuFt-VTV4vk_qTXiR4',
    appId: '1:349157902224:ios:f950d35704f4b9c7415515',
    messagingSenderId: '349157902224',
    projectId: 'springbootflutterfirebase',
    storageBucket: 'springbootflutterfirebase.firebasestorage.app',
    iosBundleId: 'com.zamambo.testapp.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvi_su4tGZ67kUpTuFt-VTV4vk_qTXiR4',
    appId: '1:349157902224:ios:f950d35704f4b9c7415515',
    messagingSenderId: '349157902224',
    projectId: 'springbootflutterfirebase',
    storageBucket: 'springbootflutterfirebase.firebasestorage.app',
    iosBundleId: 'com.zamambo.testapp.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_dMvdOAumuFUsjywOvBeMxQlIFu55BP0',
    appId: '1:349157902224:web:e0eee59042549283415515',
    messagingSenderId: '349157902224',
    projectId: 'springbootflutterfirebase',
    authDomain: 'springbootflutterfirebase.firebaseapp.com',
    storageBucket: 'springbootflutterfirebase.firebasestorage.app',
    measurementId: 'G-75DKX3WZ0D',
  );
}
