-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDskTUVJh3RXvubCY
/MO3U0idn71F6gu13pVPAIMUK26gCgYIKoZIzj0DAQehRANCAAQU/Ar1MFK+pJyW
9hdsBpvNMKVvphibbYQyPdPPBLgf4zfOoVuC+PFUMFmcn6G6+ljSINezzNkjuwDf
2vwAYEfR
-----END PRIVATE KEY-----